pipeline {
    agent any

    stages {
        stage('Build') {
            steps {
               echo "Compiling..."

               sh "cd simple-akka-http-k8s && ${tool name: 'jen_sbt', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt orderServiceCompile"
            }
        }
        stage('Unit Test') {
            steps {
               echo "Testing..."

               sh "cd simple-akka-http-k8s && ${tool name: 'jen_sbt', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt orderServiceTest"
            }
        }
        stage('Dockerfile') {
            steps {
               echo "Creating Dockerfile..."

               sh "cd simple-akka-http-k8s && ${tool name: 'jen_sbt', type: 'org.jvnet.hudson.plugins.SbtPluginBuilder$SbtInstallation'}/bin/sbt orderServiceDocker"
            }
        }
        stage('Docker Build and Push') {
            steps {
                echo "Building Docker Image..."

                script {
                    docker.withTool('jen_docker') {
                        def orderServiceImage = docker.build('vi_kas.github.io/order_service:latest', 'simple-akka-http-k8s/orderService/target/docker')
                        orderServiceImage.push()
                    }
                }
            }
        }
    }
}